import os.path
current_dir = os.path.abspath(os.getcwd())
parent_dir = os.path.dirname(current_dir)
python_interpreter = os.path.join(parent_dir, "XYKC_AI\\python.exe")
ollama_api_script_path = os.path.join(parent_dir, "XYKC_AI\\XYKC_AI_PyScripts\\ollama_api.py")
aliqwen_openai_api_script_path = os.path.join(parent_dir, "XYKC_AI\\XYKC_AI_PyScripts\\aliqwen_openai_api.py")
transformer_api_script_path = os.path.join(parent_dir, "XYKC_AI\\XYKC_AI_PyScripts\\transformers_api.py")
os.path.normpath(current_dir)
os.path.normpath(parent_dir)
os.path.normpath(python_interpreter)
os.path.normpath(ollama_api_script_path)
os.path.normpath(aliqwen_openai_api_script_path)
os.path.normpath(transformer_api_script_path)

print(current_dir)
print(parent_dir)
print(python_interpreter)
print(ollama_api_script_path)
print(aliqwen_openai_api_script_path)
print(transformer_api_script_path)